package Chapter 1_;

public class FixDegubOne
{

    Run|Debug
    public static void main(String[] args )
    {
        System.out.println(x:"Hello World!");
    }
}

/*
Spotted bugs below:
1. Class name contains a space.
2. Method name Main is capitalized.
3. Should be an array to accept command-line arguments.
4. Typo in System
5. System.out.println("Hello World!") lacks a semicolon.
6. No closing brace for the class.asd